/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej2graf1;

import com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.google.common.primitives.Floats;
import com.google.common.primitives.Ints;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
//import static sun.net.www.http.HttpClient.New;

/**
 *
 * @author libookami
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Canvas canvas;
    
    private Figura FiguraSeleccionada = null;
    private Punto puntoSeleccionado = null;

    /**
     * @return the puntoSeleccionado
     */
    public Punto getPuntoSeleccionado() {
        return puntoSeleccionado;
    }

    /**
     * @param puntoSeleccionado the puntoSeleccionado to set
     */
    public void setPuntoSeleccionado(Punto puntoSeleccionado) {
        this.puntoSeleccionado = puntoSeleccionado;
        
        if(this.puntoSeleccionado != null)
        {
            cajaPuntoX.setText((String.valueOf(getPuntoSeleccionado().getPx())));
            cajaPuntoY.setText((String.valueOf(getPuntoSeleccionado().getPy())));
        }
        else
        {
            cajaPuntoX.setText("");
            cajaPuntoY.setText("");
        }
    }
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.width = 1280;
        config.height = 720;
        config.vSyncEnabled = true;
        config.foregroundFPS = 60;
        
        canvas = new Canvas(this);
        LwjglAWTCanvas awtcanvas = new LwjglAWTCanvas(canvas, config);
        plano.add(awtcanvas.getCanvas());
        
        JLSTFiguras.setModel(canvas.ListaFiguras);
        
        
        JLSTFiguras.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                FiguraSeleccionada = JLSTFiguras.getSelectedValue();
                
                if(FiguraSeleccionada != null)
                {
                    JLST_PUNTOS.setModel(FiguraSeleccionada.getListaPuntos());
                }
            }
        });
        
        JLST_PUNTOS.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                setPuntoSeleccionado(JLST_PUNTOS.getSelectedValue());
                //System.out.println(JLST_PUNTOS.getSelectedValue().toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mantel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        plano = new javax.swing.JPanel();
        controles = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        panelFiguras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLSTFiguras = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnAgregarFig = new ej2graf1.MiButton();
        btnEditarFig = new ej2graf1.MiButton();
        btnEliminarFig = new ej2graf1.MiButton();
        panelPuntos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JLST_PUNTOS = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        cajaPuntoX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaPuntoY = new javax.swing.JTextField();
        btnEliminarPunto = new ej2graf1.MiButton();
        btnAgregarPunto = new ej2graf1.MiButton();
        btnEditarPunto = new ej2graf1.MiButton();
        jLabel3 = new javax.swing.JLabel();
        textEscala = new javax.swing.JTextField();
        panelModos = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        rotacion = new javax.swing.JPanel();
        btnRotar = new ej2graf1.MiButton();
        jLabel5 = new javax.swing.JLabel();
        cajaRotar = new javax.swing.JTextField();
        traslacion = new javax.swing.JPanel();
        btnTrasladar = new ej2graf1.MiButton();
        labelcajaTraslacionX = new javax.swing.JLabel();
        labelcajaTraslacionY = new javax.swing.JLabel();
        cajaTraslacionX = new javax.swing.JTextField();
        cajaTraslacionY = new javax.swing.JTextField();
        escalado = new javax.swing.JPanel();
        btnEscalar = new ej2graf1.MiButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajaEscalarX = new javax.swing.JTextField();
        cajaEscalarY = new javax.swing.JTextField();
        sesgo = new javax.swing.JPanel();
        btnSesgar = new ej2graf1.MiButton();
        boxSesgo = new javax.swing.JComboBox<>();
        cajaSesgar = new javax.swing.JTextField();
        miButton1 = new ej2graf1.MiButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        guardarItem = new javax.swing.JMenuItem();
        cargarItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(420, 420));

        mantel.setBackground(new java.awt.Color(255, 153, 255));
        mantel.setPreferredSize(new java.awt.Dimension(1090, 720));

        jSplitPane1.setDividerLocation(350);

        plano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        plano.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane1.setRightComponent(plano);

        jSplitPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane2.setDividerLocation(150);

        panelFiguras.setBackground(new java.awt.Color(102, 102, 102));
        panelFiguras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFiguras.setMaximumSize(new java.awt.Dimension(700, 700));
        panelFiguras.setPreferredSize(new java.awt.Dimension(149, 670));

        jScrollPane1.setViewportView(JLSTFiguras);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        btnAgregarFig.setText("Agregar");
        btnAgregarFig.setColorNormal(new java.awt.Color(0, 255, 0));
        btnAgregarFig.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnAgregarFig.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnAgregarFig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFigActionPerformed(evt);
            }
        });

        btnEditarFig.setText("Editar");
        btnEditarFig.setColorNormal(new java.awt.Color(0, 255, 0));
        btnEditarFig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFigActionPerformed(evt);
            }
        });

        btnEliminarFig.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarFig.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFig.setText("Eliminar");
        btnEliminarFig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarFig, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFigurasLayout = new javax.swing.GroupLayout(panelFiguras);
        panelFiguras.setLayout(panelFigurasLayout);
        panelFigurasLayout.setHorizontalGroup(
            panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFigurasLayout.setVerticalGroup(
            panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(panelFiguras);

        panelPuntos.setBackground(new java.awt.Color(102, 102, 102));
        panelPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPuntos.setPreferredSize(new java.awt.Dimension(199, 670));

        jScrollPane2.setViewportView(JLST_PUNTOS);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cajaPuntoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPuntoXActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Y:");

        btnEliminarPunto.setBackground(new java.awt.Color(250, 0, 0));
        btnEliminarPunto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPunto.setText("Eliminar");
        btnEliminarPunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPuntoActionPerformed(evt);
            }
        });

        btnAgregarPunto.setText("Agregar");
        btnAgregarPunto.setColorNormal(new java.awt.Color(0, 255, 0));
        btnAgregarPunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPuntoActionPerformed(evt);
            }
        });

        btnEditarPunto.setText("Editar");
        btnEditarPunto.setColorNormal(new java.awt.Color(0, 255, 0));
        btnEditarPunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAgregarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaPuntoX))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaPuntoY, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaPuntoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaPuntoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escala:");

        textEscala.setText("20");
        textEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEscalaActionPerformed(evt);
            }
        });
        textEscala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEscalaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelPuntosLayout = new javax.swing.GroupLayout(panelPuntos);
        panelPuntos.setLayout(panelPuntosLayout);
        panelPuntosLayout.setHorizontalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelPuntosLayout.createSequentialGroup()
                        .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPuntosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPuntosLayout.setVerticalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textEscala))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(panelPuntos);

        panelModos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRotar.setText("Rotar");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ángulo:");

        javax.swing.GroupLayout rotacionLayout = new javax.swing.GroupLayout(rotacion);
        rotacion.setLayout(rotacionLayout);
        rotacionLayout.setHorizontalGroup(
            rotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rotacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRotar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rotacionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaRotar)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        rotacionLayout.setVerticalGroup(
            rotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rotacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajaRotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnRotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab.addTab("Rotación", rotacion);

        btnTrasladar.setText("Trasladar");
        btnTrasladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasladarActionPerformed(evt);
            }
        });

        labelcajaTraslacionX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcajaTraslacionX.setText("x:");

        labelcajaTraslacionY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcajaTraslacionY.setText("y:");

        javax.swing.GroupLayout traslacionLayout = new javax.swing.GroupLayout(traslacion);
        traslacion.setLayout(traslacionLayout);
        traslacionLayout.setHorizontalGroup(
            traslacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(traslacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(traslacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(traslacionLayout.createSequentialGroup()
                        .addComponent(labelcajaTraslacionX)
                        .addGap(6, 6, 6)
                        .addComponent(cajaTraslacionX, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelcajaTraslacionY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaTraslacionY, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        traslacionLayout.setVerticalGroup(
            traslacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, traslacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(traslacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcajaTraslacionX)
                    .addComponent(labelcajaTraslacionY)
                    .addComponent(cajaTraslacionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaTraslacionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab.addTab("Traslación", traslacion);

        btnEscalar.setText("Escalar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("x:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("y:");

        javax.swing.GroupLayout escaladoLayout = new javax.swing.GroupLayout(escalado);
        escalado.setLayout(escaladoLayout);
        escaladoLayout.setHorizontalGroup(
            escaladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escaladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escaladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(escaladoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaEscalarX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaEscalarY)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        escaladoLayout.setVerticalGroup(
            escaladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escaladoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(escaladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cajaEscalarX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaEscalarY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab.addTab("Escalado", escalado);

        btnSesgar.setText("Sesgar");

        boxSesgo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boxSesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x", "y" }));

        javax.swing.GroupLayout sesgoLayout = new javax.swing.GroupLayout(sesgo);
        sesgo.setLayout(sesgoLayout);
        sesgoLayout.setHorizontalGroup(
            sesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesgoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boxSesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSesgar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaSesgar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        sesgoLayout.setVerticalGroup(
            sesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sesgoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaSesgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSesgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab.addTab("Sesgado", sesgo);

        javax.swing.GroupLayout panelModosLayout = new javax.swing.GroupLayout(panelModos);
        panelModos.setLayout(panelModosLayout);
        panelModosLayout.setHorizontalGroup(
            panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelModosLayout.setVerticalGroup(
            panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout controlesLayout = new javax.swing.GroupLayout(controles);
        controles.setLayout(controlesLayout);
        controlesLayout.setHorizontalGroup(
            controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelModos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        controlesLayout.setVerticalGroup(
            controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesLayout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelModos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controles);

        miButton1.setBackground(new java.awt.Color(0, 0, 255));
        miButton1.setForeground(new java.awt.Color(255, 255, 255));
        miButton1.setText("Acerca de");
        miButton1.setColorNormal(new java.awt.Color(0, 0, 255));
        miButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mantelLayout = new javax.swing.GroupLayout(mantel);
        mantel.setLayout(mantelLayout);
        mantelLayout.setHorizontalGroup(
            mantelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mantelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mantelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                    .addGroup(mantelLayout.createSequentialGroup()
                        .addComponent(miButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mantelLayout.setVerticalGroup(
            mantelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mantelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        guardarItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        guardarItem.setText("Guardar");
        guardarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarItemActionPerformed(evt);
            }
        });
        jMenu1.add(guardarItem);

        cargarItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        cargarItem.setText("Cargar");
        cargarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarItemActionPerformed(evt);
            }
        });
        jMenu1.add(cargarItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mantel, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mantel, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEscalaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Escala: " + textEscala.getText());
        Canvas.setEscala(Integer.valueOf(textEscala.getText()));
    }//GEN-LAST:event_textEscalaActionPerformed

    private void textEscalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEscalaKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        String text = textEscala.getText();

        // Verificar si es un dígito
        if (!Character.isDigit(key)) {
            evt.consume(); // Consumir evento si no es dígito
            return;
        }
        if (textEscala.getText().length() == 2) {
            evt.consume();
        }
    }//GEN-LAST:event_textEscalaKeyTyped

    private void btnAgregarFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFigActionPerformed
        // TODO add your handling code here:
        if(!jTextField4.getText().isEmpty())
        {
            canvas.ListaFiguras.addElement(new Figura(jTextField4.getText()));
        }
    }//GEN-LAST:event_btnAgregarFigActionPerformed

    private void btnEditarFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFigActionPerformed
        // TODO add your handling code here:
        if(!jTextField4.getText().isEmpty() && FiguraSeleccionada != null)
        {
            FiguraSeleccionada.setNombre(jTextField4.getText());
        }
        
        JLSTFiguras.updateUI();
    }//GEN-LAST:event_btnEditarFigActionPerformed

    private void btnEliminarFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFigActionPerformed
        // TODO add your handling code here:
        if(FiguraSeleccionada != null)
        {
            puntoSeleccionado = null;
            canvas.ListaFiguras.removeElement(FiguraSeleccionada);
        }
        
        JLSTFiguras.updateUI();
    }//GEN-LAST:event_btnEliminarFigActionPerformed

    private void btnEliminarPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPuntoActionPerformed
        // TODO add your handling code here:
        if(FiguraSeleccionada != null && getPuntoSeleccionado() != null)
        {
            FiguraSeleccionada.getListaPuntos().removeElement(getPuntoSeleccionado());
        }
        
        JLST_PUNTOS.updateUI();
    }//GEN-LAST:event_btnEliminarPuntoActionPerformed

    private void btnAgregarPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPuntoActionPerformed
        // TODO add your handling code here:
        if(FiguraSeleccionada != null){
            int px = Ints.tryParse(cajaPuntoX.getText()).intValue();
            int py = Ints.tryParse(cajaPuntoY.getText()).intValue();
            
            cajaPuntoX.setText(""+px);
            cajaPuntoX.setText(""+py);
            
            FiguraSeleccionada.getListaPuntos().addElement(new Punto(px,py));
        }
        
        JLST_PUNTOS.updateUI();
    }//GEN-LAST:event_btnAgregarPuntoActionPerformed

    private void btnEditarPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPuntoActionPerformed
        // TODO add your handling code here:
        if(getPuntoSeleccionado() != null)
        {
            getPuntoSeleccionado().setPx(Integer.parseInt(cajaPuntoX.getText()));
            getPuntoSeleccionado().setPy(Integer.parseInt(cajaPuntoY.getText()));
        }
        
        JLST_PUNTOS.updateUI();
    }//GEN-LAST:event_btnEditarPuntoActionPerformed

    private void miButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Graficación grupo 1 - Equipo 4"
                + "\n\nBazán Calderón Christian Emmanuel"
                + "\nFranco Vidrio Guillermo"
                + "\nSánchez Arenas Perla Vanessa"
                + "\nSedeño García José Daniel"
                + "\nVillanueva Gutiérrez Miriam Alejandra"
                + "\nVillafán Contreras Luis Gustavo");
    }//GEN-LAST:event_miButton1ActionPerformed

    private void cajaPuntoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPuntoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPuntoXActionPerformed

    private void btnTrasladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladarActionPerformed
        // TODO add your handling code here:
        if(FiguraSeleccionada!=null){
            if(cajaTraslacionX.getText().isEmpty() || cajaTraslacionY.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Debes llenar los dos campos");
            }else{
                float tx = Float.parseFloat(cajaTraslacionX.getText());
                float ty = Float.parseFloat(cajaTraslacionY.getText());
                
                Figura c = null;
                
                float nuevox, nuevoy;
                int i;
                int x = c.getListaPuntos().getSize();
                 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar una figura");
        }
    }//GEN-LAST:event_btnTrasladarActionPerformed

    private void guardarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarItemActionPerformed
        // TODO add your handling code here:
        String s = "";

        String path = System.getProperty("user.home")+ File.separator + "figurasG.txt";
        for(int i=0; i < canvas.ListaFiguras.size(); i++){
            Figura f = canvas.ListaFiguras.get(i);
            s+=f.getNombre();
            
            for(int j=0; j< f.getListaPuntos().size(); j++){
                Punto p = f.getListaPuntos().get(j);
                        
                s += "," + p.getPx() + "," + p.getPy();
            }
            s += "\n";
        }
        
        
        System.out.println("El contendido del archivo será " +s);
          
        
        try(BufferedWriter writer = new BufferedWriter(new FileWriter(path)))
        {
          writer.append(s);
          writer.close();
        } catch (IOException ioex) {
            JOptionPane.showMessageDialog(this, "Error de IO" + ioex.getMessage());
            
        }
            
    }//GEN-LAST:event_guardarItemActionPerformed

    private void cargarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarItemActionPerformed
        // TODO add your handling code here:
        String path = System.getProperty("user.home")+ File.separator + "figurasG.txt";
        
       
        try(BufferedReader reader = new BufferedReader(new FileReader(path))){
            String linea;
            while((linea = reader.readLine()) != null){
                System.out.println(linea);
                String[] tokens = linea.split(","); //separar todo los eparado por coma
                
                Figura f = new Figura(tokens[0]);
                for (int i = 1; i < tokens.length; i+=2) {
                    //
                    float x = Floats.tryParse(tokens[i]);
                    float y = Floats.tryParse(tokens[i+1]);
                    
                    Punto p = new Punto(x, y);
                    f.getListaPuntos().addElement(p);
                }
                canvas.ListaFiguras.addElement(f); //traemos el nombre de la figura
                
            }
            
        }
        catch(IOException iox){
            JOptionPane.showMessageDialog(null, "hola");
        }
    }//GEN-LAST:event_cargarItemActionPerformed
    Canvas y;

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Figura> JLSTFiguras;
    private javax.swing.JList<Punto> JLST_PUNTOS;
    private javax.swing.JComboBox<String> boxSesgo;
    private ej2graf1.MiButton btnAgregarFig;
    private ej2graf1.MiButton btnAgregarPunto;
    private ej2graf1.MiButton btnEditarFig;
    private ej2graf1.MiButton btnEditarPunto;
    private ej2graf1.MiButton btnEliminarFig;
    private ej2graf1.MiButton btnEliminarPunto;
    private ej2graf1.MiButton btnEscalar;
    private ej2graf1.MiButton btnRotar;
    private ej2graf1.MiButton btnSesgar;
    private ej2graf1.MiButton btnTrasladar;
    private javax.swing.JTextField cajaEscalarX;
    private javax.swing.JTextField cajaEscalarY;
    private javax.swing.JTextField cajaPuntoX;
    private javax.swing.JTextField cajaPuntoY;
    private javax.swing.JTextField cajaRotar;
    private javax.swing.JTextField cajaSesgar;
    private javax.swing.JTextField cajaTraslacionX;
    private javax.swing.JTextField cajaTraslacionY;
    private javax.swing.JMenuItem cargarItem;
    private javax.swing.JPanel controles;
    private javax.swing.JPanel escalado;
    private javax.swing.JMenuItem guardarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labelcajaTraslacionX;
    private javax.swing.JLabel labelcajaTraslacionY;
    private javax.swing.JPanel mantel;
    private ej2graf1.MiButton miButton1;
    private javax.swing.JPanel panelFiguras;
    private javax.swing.JPanel panelModos;
    private javax.swing.JPanel panelPuntos;
    private javax.swing.JPanel plano;
    private javax.swing.JPanel rotacion;
    private javax.swing.JPanel sesgo;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField textEscala;
    private javax.swing.JPanel traslacion;
    // End of variables declaration//GEN-END:variables
}
