/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej2graf1;

import com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.google.common.primitives.Ints;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author libookami
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Canvas canvas;
    
    private Figura FiguraSeleccionada = null;
    private Punto puntoSeleccionado = null;

    /**
     * @return the puntoSeleccionado
     */
    public Punto getPuntoSeleccionado() {
        return puntoSeleccionado;
    }

    /**
     * @param puntoSeleccionado the puntoSeleccionado to set
     */
    public void setPuntoSeleccionado(Punto puntoSeleccionado) {
        this.puntoSeleccionado = puntoSeleccionado;
        
        if(this.puntoSeleccionado != null)
        {
            jTextField1.setText((String.valueOf(getPuntoSeleccionado().getPx())));
            jTextField2.setText((String.valueOf(getPuntoSeleccionado().getPy())));
        }
        else
        {
            jTextField1.setText("");
            jTextField2.setText("");
        }
    }
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.width = 1280;
        config.height = 720;
        config.vSyncEnabled = true;
        config.foregroundFPS = 60;
        
        canvas = new Canvas(this);
        LwjglAWTCanvas awtcanvas = new LwjglAWTCanvas(canvas, config);
        jPanel1.add(awtcanvas.getCanvas());
        
        JLSTFiguras.setModel(canvas.ListaFiguras);
        
        
        JLSTFiguras.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                FiguraSeleccionada = JLSTFiguras.getSelectedValue();
                
                if(FiguraSeleccionada != null)
                {
                    JLST_PUNTOS.setModel(FiguraSeleccionada.getListaPuntos());
                }
            }
        });
        
        JLST_PUNTOS.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                setPuntoSeleccionado(JLST_PUNTOS.getSelectedValue());
                //System.out.println(JLST_PUNTOS.getSelectedValue().toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mantel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        panelFiguras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLSTFiguras = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnAgregarFig = new ej2graf1.MiButton();
        btnEditarFig = new ej2graf1.MiButton();
        btnEditarFig1 = new ej2graf1.MiButton();
        panelPuntos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JLST_PUNTOS = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnEliminarPunto = new ej2graf1.MiButton();
        btnAgregarPunto = new ej2graf1.MiButton();
        btnEditarPunto = new ej2graf1.MiButton();
        jLabel3 = new javax.swing.JLabel();
        textEscala = new javax.swing.JTextField();
        panelModos = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        rotacion = new javax.swing.JPanel();
        traslacion = new javax.swing.JPanel();
        escalado = new javax.swing.JPanel();
        sesgo = new javax.swing.JPanel();
        miButton1 = new ej2graf1.MiButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(420, 420));

        mantel.setBackground(new java.awt.Color(255, 153, 255));
        mantel.setPreferredSize(new java.awt.Dimension(1090, 720));

        jSplitPane1.setDividerLocation(350);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane1.setRightComponent(jPanel1);

        jSplitPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane2.setDividerLocation(150);

        panelFiguras.setBackground(new java.awt.Color(102, 102, 102));
        panelFiguras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFiguras.setMaximumSize(new java.awt.Dimension(700, 700));
        panelFiguras.setPreferredSize(new java.awt.Dimension(149, 670));

        jScrollPane1.setViewportView(JLSTFiguras);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        btnAgregarFig.setText("Agregar");
        btnAgregarFig.setColorNormal(new java.awt.Color(0, 255, 0));
        btnAgregarFig.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnAgregarFig.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnAgregarFig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFigActionPerformed(evt);
            }
        });

        btnEditarFig.setText("Editar");
        btnEditarFig.setColorNormal(new java.awt.Color(0, 255, 0));
        btnEditarFig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFigActionPerformed(evt);
            }
        });

        btnEditarFig1.setBackground(new java.awt.Color(255, 0, 0));
        btnEditarFig1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarFig1.setText("Eliminar");
        btnEditarFig1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarFig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFig1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditarFig1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarFig, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarFig, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarFig1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFigurasLayout = new javax.swing.GroupLayout(panelFiguras);
        panelFiguras.setLayout(panelFigurasLayout);
        panelFigurasLayout.setHorizontalGroup(
            panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFigurasLayout.setVerticalGroup(
            panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(panelFiguras);

        panelPuntos.setBackground(new java.awt.Color(102, 102, 102));
        panelPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPuntos.setPreferredSize(new java.awt.Dimension(199, 670));

        jScrollPane2.setViewportView(JLST_PUNTOS);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Y:");

        btnEliminarPunto.setBackground(new java.awt.Color(250, 0, 0));
        btnEliminarPunto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPunto.setText("Eliminar");
        btnEliminarPunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPuntoActionPerformed(evt);
            }
        });

        btnAgregarPunto.setText("Agregar");
        btnAgregarPunto.setColorNormal(new java.awt.Color(0, 255, 0));
        btnAgregarPunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPuntoActionPerformed(evt);
            }
        });

        btnEditarPunto.setText("Editar");
        btnEditarPunto.setColorNormal(new java.awt.Color(0, 255, 0));
        btnEditarPunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAgregarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escala:");

        textEscala.setText("20");
        textEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEscalaActionPerformed(evt);
            }
        });
        textEscala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEscalaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelPuntosLayout = new javax.swing.GroupLayout(panelPuntos);
        panelPuntos.setLayout(panelPuntosLayout);
        panelPuntosLayout.setHorizontalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelPuntosLayout.createSequentialGroup()
                        .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPuntosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPuntosLayout.setVerticalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(panelPuntos);

        panelModos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout rotacionLayout = new javax.swing.GroupLayout(rotacion);
        rotacion.setLayout(rotacionLayout);
        rotacionLayout.setHorizontalGroup(
            rotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        rotacionLayout.setVerticalGroup(
            rotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tab.addTab("Rot", rotacion);

        javax.swing.GroupLayout traslacionLayout = new javax.swing.GroupLayout(traslacion);
        traslacion.setLayout(traslacionLayout);
        traslacionLayout.setHorizontalGroup(
            traslacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        traslacionLayout.setVerticalGroup(
            traslacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tab.addTab("Tras", traslacion);

        javax.swing.GroupLayout escaladoLayout = new javax.swing.GroupLayout(escalado);
        escalado.setLayout(escaladoLayout);
        escaladoLayout.setHorizontalGroup(
            escaladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        escaladoLayout.setVerticalGroup(
            escaladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tab.addTab("Escal", escalado);

        javax.swing.GroupLayout sesgoLayout = new javax.swing.GroupLayout(sesgo);
        sesgo.setLayout(sesgoLayout);
        sesgoLayout.setHorizontalGroup(
            sesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        sesgoLayout.setVerticalGroup(
            sesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tab.addTab("Sesgo", sesgo);

        javax.swing.GroupLayout panelModosLayout = new javax.swing.GroupLayout(panelModos);
        panelModos.setLayout(panelModosLayout);
        panelModosLayout.setHorizontalGroup(
            panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelModosLayout.setVerticalGroup(
            panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelModos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelModos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        miButton1.setBackground(new java.awt.Color(0, 0, 255));
        miButton1.setForeground(new java.awt.Color(255, 255, 255));
        miButton1.setText("Acerca de");
        miButton1.setColorNormal(new java.awt.Color(0, 0, 255));
        miButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mantelLayout = new javax.swing.GroupLayout(mantel);
        mantel.setLayout(mantelLayout);
        mantelLayout.setHorizontalGroup(
            mantelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mantelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mantelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                    .addGroup(mantelLayout.createSequentialGroup()
                        .addComponent(miButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mantelLayout.setVerticalGroup(
            mantelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mantelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mantel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mantel, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEscalaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Escala: " + textEscala.getText());
        Canvas.setEscala(Integer.valueOf(textEscala.getText()));
    }//GEN-LAST:event_textEscalaActionPerformed

    private void textEscalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEscalaKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        String text = textEscala.getText();

        // Verificar si es un dígito
        if (!Character.isDigit(key)) {
            evt.consume(); // Consumir evento si no es dígito
            return;
        }
        if (textEscala.getText().length() == 2) {
            evt.consume();
        }
    }//GEN-LAST:event_textEscalaKeyTyped

    private void btnAgregarFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFigActionPerformed
        // TODO add your handling code here:
        if(!jTextField4.getText().isEmpty())
        {
            canvas.ListaFiguras.addElement(new Figura(jTextField4.getText()));
        }
    }//GEN-LAST:event_btnAgregarFigActionPerformed

    private void btnEditarFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFigActionPerformed
        // TODO add your handling code here:
        if(!jTextField4.getText().isEmpty() && FiguraSeleccionada != null)
        {
            FiguraSeleccionada.setNombre(jTextField4.getText());
        }
        
        JLSTFiguras.updateUI();
    }//GEN-LAST:event_btnEditarFigActionPerformed

    private void btnEditarFig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFig1ActionPerformed
        // TODO add your handling code here:
        if(FiguraSeleccionada != null)
        {
            puntoSeleccionado = null;
            canvas.ListaFiguras.removeElement(FiguraSeleccionada);
        }
        
        JLSTFiguras.updateUI();
    }//GEN-LAST:event_btnEditarFig1ActionPerformed

    private void btnEliminarPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPuntoActionPerformed
        // TODO add your handling code here:
        if(FiguraSeleccionada != null && getPuntoSeleccionado() != null)
        {
            FiguraSeleccionada.getListaPuntos().removeElement(getPuntoSeleccionado());
        }
        
        JLST_PUNTOS.updateUI();
    }//GEN-LAST:event_btnEliminarPuntoActionPerformed

    private void btnAgregarPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPuntoActionPerformed
        // TODO add your handling code here:
                if(FiguraSeleccionada != null)
        {
            int px = Ints.tryParse(jTextField1.getText()).intValue();
            int py = Ints.tryParse(jTextField2.getText()).intValue();
            
            jTextField1.setText(""+px);
            jTextField1.setText(""+py);
            
            FiguraSeleccionada.getListaPuntos().addElement(new Punto(px,py));
        }
        
        JLST_PUNTOS.updateUI();
    }//GEN-LAST:event_btnAgregarPuntoActionPerformed

    private void btnEditarPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPuntoActionPerformed
        // TODO add your handling code here:
        if(getPuntoSeleccionado() != null)
        {
            getPuntoSeleccionado().setPx(Integer.parseInt(jTextField1.getText()));
            getPuntoSeleccionado().setPy(Integer.parseInt(jTextField2.getText()));
        }
        
        JLST_PUNTOS.updateUI();
    }//GEN-LAST:event_btnEditarPuntoActionPerformed

    private void miButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Graficación grupo 1 - Equipo 4"
                + "\n\nBazán Calderón Christian Emmanuel"
                + "\nFranco Vidrio Guillermo"
                + "\nSánchez Arenas Perla Vanessa"
                + "\nSedeño García José Daniel"
                + "\nVillanueva Gutiérrez Miriam Alejandra"
                + "\nVillafán Contreras Luis Gustavo");
    }//GEN-LAST:event_miButton1ActionPerformed
    Canvas y;

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Figura> JLSTFiguras;
    private javax.swing.JList<Punto> JLST_PUNTOS;
    private ej2graf1.MiButton btnAgregarFig;
    private ej2graf1.MiButton btnAgregarPunto;
    private ej2graf1.MiButton btnEditarFig;
    private ej2graf1.MiButton btnEditarFig1;
    private ej2graf1.MiButton btnEditarPunto;
    private ej2graf1.MiButton btnEliminarPunto;
    private javax.swing.JPanel escalado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel mantel;
    private ej2graf1.MiButton miButton1;
    private javax.swing.JPanel panelFiguras;
    private javax.swing.JPanel panelModos;
    private javax.swing.JPanel panelPuntos;
    private javax.swing.JPanel rotacion;
    private javax.swing.JPanel sesgo;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField textEscala;
    private javax.swing.JPanel traslacion;
    // End of variables declaration//GEN-END:variables
}
